services:
  rag_api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rag_api
    volumes:
      - .:/src
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: uvicorn app.api.main:app --host 0.0.0.0 --port 8000 --reload

  rag_ui:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: rag_ui
    volumes:
      - .:/src
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - rag_api
    command: streamlit run app/ui/app.py